In [7]:
#Example 1
import time 
import numpy 
import array 

In [8]:
a = array.array('i') 
for i in range(200): 
    a.append(i); 

In [9]:
b = array.array('i') 
for i in range(200, 400): 
    b.append(i) 

In [10]:
tic = time.process_time() 
outer_product = numpy.zeros((200, 200)) 
  
for i in range(len(a)): 
   for j in range(len(b)): 
      outer_product[i][j]= a[i]*b[j] 
  
toc = time.process_time() 

In [11]:
print("outer_product = "+ str(outer_product)); 
print("Computation time = "+str(1000*(toc - tic ))+"ms") 
   
n_tic = time.process_time() 
outer_product = numpy.outer(a, b) 
n_toc = time.process_time() 

outer_product = [[    0.     0.     0. ...     0.     0.     0.]
 [  200.   201.   202. ...   397.   398.   399.]
 [  400.   402.   404. ...   794.   796.   798.]
 ...
 [39400. 39597. 39794. ... 78209. 78406. 78603.]
 [39600. 39798. 39996. ... 78606. 78804. 79002.]
 [39800. 39999. 40198. ... 79003. 79202. 79401.]]
Computation time = 46.875ms


In [12]:
print("outer_product = "+str(outer_product)); 
print("\nComputation time = "+str(1000*(n_toc - n_tic ))+"ms") 

outer_product = [[    0     0     0 ...     0     0     0]
 [  200   201   202 ...   397   398   399]
 [  400   402   404 ...   794   796   798]
 ...
 [39400 39597 39794 ... 78209 78406 78603]
 [39600 39798 39996 ... 78606 78804 79002]
 [39800 39999 40198 ... 79003 79202 79401]]

Computation time = 0.0ms


In [30]:
#Example 2
import numpy as np
import time

In [31]:
a = np.arange(10000000)
b = np.arange(10000000)

In [38]:
# pure Python outer product implementation
tic = time.process_time()

dot_product = 0
for i in range(len(a)):
    dot_product += a[i] * b[i]

toc = time.process_time()

print("python_dot_product = "+ str(dot_product))
print("Time = "+str(1000*(toc - tic ))+"ms\n")

C:\Users\AMD62018\anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: overflow encountered in long_scalars
  


python_dot_product = -1039031360
Time = 43546.875ms



In [39]:
n_tic = time.process_time()
dot_product = np.dot(a, b)
n_toc = time.process_time()
print("numpy_dot_product = "+str(dot_product))
print("Time = "+str(1000*(n_toc - n_tic ))+"ms")

numpy_dot_product = -1039031360
Time = 15.625ms
